spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db.rtfxnjhmvzpwaknakwcj.supabase.co:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  google:
    allowTestToken: false
  mail:
    mode: smtp
